language: python
python:
  - "3.5"
cache: pip

install:
  - pip install -r requirements.txt --quiet

script:
  - wget "$LIST_URL" -O list.txt -q
  - wget "$CONF" -O coursera-dl.conf -q
  - touch log.txt
  - |
    while IFS='' read -r line || [[ -n "$line" ]]; do

        # strip trailing line break
        line=$(echo $line|tr -d '\r')

        # skip comments
        if [[ $line != "#"* ]] && [[ $line != "" ]]; then
          coursera-dl "$line" > log.txt
        fi
    done < list.txt
  - python convert.py
